name: carebea
version: 1.0.0+1
publish_to: none
description: Carebea Mobile App.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  dropdown_search: 5.0.2
  table_calendar: 3.0.6
  get: 4.6.5
  location: ^4.4.0
  permission_handler: ^10.0.0
  dotted_line: 3.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Regular.ttf
        - weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
        - weight: 500
  uses-material-design: true

