name: carebea
version: 1.0.0+1
publish_to: none
description: Carebea Mobile App.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  dropdown_search: 5.0.2
  get: 4.6.5
  location: ^4.4.0
  permission_handler: ^10.0.0
  slide_to_confirm: ^1.1.0
  table_calendar: 3.0.6
  dotted_line: 3.1.0
  flutter_local_notifications: 9.7.0
  firebase_messaging: 11.4.4
  firebase_core: 1.19.1
  firebase_crashlytics: 2.8.4
  json_serializable: 6.3.1
  json_annotation: 4.6.0
  http: 0.13.4
  logger: 1.1.0
  shared_preferences: 2.0.15
  connectivity_plus: 2.3.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  build_runner: 2.2.0
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Regular.ttf
        - weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
        - weight: 500
  uses-material-design: true

