name: admin_580_tech
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
#  auto_route: 5.0.2
  auto_route: 7.7.0
  flutter_bloc: ^8.1.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.1.0
  flutter_svg: ^2.0.7
  intl: ^0.18.0
  fl_chart: ^0.55.1
  data_table_2: ^2.3.6
  url_launcher: ^6.1.5
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.4+2
  hive_flutter: ^1.1.0
  carousel_slider: ^4.1.1
  desktop_drop: ^0.4.0
  flutter_excel: ^1.0.1
  file_picker: ^5.2.5
  image_picker: ^0.8.9
  dropdown_button2: ^1.9.2
  dropdown_search: ^5.0.6
  retrofit: ^3.3.1
  dio: 4.0.6
  pretty_dio_logger: ^1.2.0-beta-1
  cached_network_image: ^3.2.0
  shimmer: ^2.0.0
  dartz: ^0.10.1
  cupertino_icons: ^1.0.2
  google_fonts:
  flutter_switch: ^0.3.2
  dotted_border: ^2.0.0+3
  percent_indicator: ^4.2.3
  flutter_rating_bar: 4.0.1
  table_calendar:
#  webviewx: ^0.2.2
  get_it:
  flutter_staggered_grid_view: ^0.6.2
  shared_preferences: ^2.2.0
  flash: ^3.0.5+1
  amplify_auth_cognito: ^1.2.1
  amplify_flutter: ^1.2.1
  amplify_storage_s3: ^1.2.1
  flutter_spinkit: ^5.2.0
  pdf_render: ^1.4.0
  html: ^0.15.4
  google_map_location_picker_flutter:
    git: https://github.com/AdarshSeroo/google_map_location_picker_flutter.git






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  retrofit_generator: ^4.2.0
  freezed: ^2.1.0+1
  auto_route_generator: ^7.2.0
  json_serializable: ^6.7.1


dependency_overrides:
  #auto_route: 6.0.0










flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

