name: carebea
version: 1.2.24+26
publish_to: none
description: Carebea Mobile App.
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  connectivity_plus: 2.3.5
  cupertino_icons: ^1.0.2
  dotted_line: 3.1.0
  dropdown_search: ^5.0.2
  firebase_core: 1.19.1
  firebase_crashlytics: 2.8.4
  firebase_messaging: 11.4.4
  flutter:
    sdk: flutter
  flutter_local_notifications: 9.7.0
  flutter_typeahead: ^4.0.0
  fluttertoast: 8.0.9
  get: 4.6.5
  google_maps_flutter: ^2.1.10
  http: 0.13.4
  intl: ^0.17.0
  json_annotation: 4.6.0
  json_serializable: 6.3.1
  location: ^4.4.0
  logger: 1.1.0
  majascan: ^0.5.0
  open_file: ^3.2.1
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  restart_app: ^1.1.0+1
  share_plus: ^4.0.10+1
  shared_preferences: 2.0.15
  slide_to_confirm: ^1.1.0
  table_calendar: 3.0.6
  url_launcher: ^6.1.5
  dio: ^4.0.6

dev_dependencies:
  build_runner: 2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/images/sr-home-icons/
    - assets/images/delivery-home-icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
        - weight: 500
  uses-material-design: true
